#!/bin/bash

# This is a test script for displaying YouTube videos with the
# yt-surl library. QuickTime Player is used to stream the video.
# Additionaly with the -d option the video may be downloaded.

function printUsage {
    echo "usage: playYTvideo [<YouTube video URL>|<YouTube video id>] [-d <output file>]"
}

if [ $# -gt 0 ]  
then
    echo "Retrieving video info..."
    
    URL=`./test.out $1`
    URL_LEN=`echo $URL | wc -c`
    
    if [ $URL_LEN -gt 150 ] 
    then
	if [ $# -eq 1 ]
	then
	    echo "Launching video in QuickTime Player"
	    open -a "/Applications/QuickTime Player.app" $URL
	elif [ $# -eq 3 ]
	then
	    if [ "$2" == "-d" ]
	    then
		echo "Downloading video to $3"
		curl -o $3 --location $URL
	    else
		printUsage
	    fi
	fi
    else
	echo $URL
    fi
else    	
    printUsage
fi

